---
base_url: "https://mysite.com"
static_dir: "static"
per_page: 50

# Each entry can have multiple collection of tags (list of strings) in addition to the
# categories. For instance, a directory of fonts could have multiple meaningful
# tag collections per entry such as:
# types = [serif, sans-serif, display, script]
# mood = [retro, distressed, cool]
# tag = [yep, nope, etc]
taxonomies: ["style", "mood"]

site_name: "Transportation System"
site_header: "Transportation System"
site_description: "Our website serves as an online platform that provides information, services, and resources related to transportation. These websites are designed to offer convenience and accessibility to users seeking various transportation options, whether it's for local commuting, long-distance travel, or specialized transportation services. "
page_title: "{category} - Directory of cool things."
meta_description: "Directory of {category} in cool things. "
